./adaptiveDTW ./50words/50words_TRAIN ./50words/50words_TEST 0
./adaptiveDTW ./Adiac/Adiac_TRAIN ./Adiac/Adiac_TEST 0
./adaptiveDTW ./AIBO/Sony_TRAIN ./AIBO/Sony_TEST 0
./adaptiveDTW ./arrowhead/arrowhead_TRAIN ./arrowhead/arrowhead_TEST 0
./adaptiveDTW ./ARSim/ARSim_TRAIN ./ARSim/ARSim_TEST 0
./adaptiveDTW ./Beef/Beef_TRAIN ./Beef/Beef_TEST 0
./adaptiveDTW ./CBF/CBF_TRAIN ./CBF/CBF_TEST 0
./adaptiveDTW ./ChlorineConcentration/ChlorineConcentration_TRAIN ./ChlorineConcentration/ChlorineConcentration_TEST 0
./adaptiveDTW ./CinC_ECG_torso/CinC_ECG_torso_TRAIN ./CinC_ECG_torso/CinC_ECG_torso_TEST 0
./adaptiveDTW ./Coffee/Coffee_TRAIN ./Coffee/Coffee_TEST 0
./adaptiveDTW ./Cricket_X/Cricket_X_TRAIN ./Cricket_X/Cricket_X_TEST 0
./adaptiveDTW ./Cricket_Y/Cricket_Y_TRAIN ./Cricket_Y/Cricket_Y_TEST 0
./adaptiveDTW ./Cricket_Z/Cricket_Z_TRAIN ./Cricket_Z/Cricket_Z_TEST 0
./adaptiveDTW ./Cricket/Cricket_TRAIN ./Cricket/Cricket_TEST 0
./adaptiveDTW ./DiatomSizeReduction/DiatomSizeReduction_TRAIN ./DiatomSizeReduction/DiatomSizeReduction_TEST 0
./adaptiveDTW ./Earthquakes/Earthquakes_TRAIN ./Earthquakes/Earthquakes_TEST 0
./adaptiveDTW ./ECG200/ECG200_TRAIN ./ECG200/ECG200_TEST 0
./adaptiveDTW ./ECGFiveDays/ECGFiveDays_TRAIN ./ECGFiveDays/ECGFiveDays_TEST 0
./adaptiveDTW ./ElectricDevices/ElectricDevices_TRAIN ./ElectricDevices/ElectricDevices_TEST 0
./adaptiveDTW ./FaceAll/FaceAll_TRAIN ./FaceAll/FaceAll_TEST 0
./adaptiveDTW ./FaceFour/FaceFour_TRAIN ./FaceFour/FaceFour_TEST 0
./adaptiveDTW ./FacesUCR/FacesUCR_TRAIN ./FacesUCR/FacesUCR_TEST 0
./adaptiveDTW ./fish/FISH_TRAIN ./fish/FISH_TEST 0
./adaptiveDTW ./FordA/Ford_A_TRAIN ./FordA/Ford_A_TEST 0
./adaptiveDTW ./FordB/Ford_B_TRAIN ./FordB/Ford_B_TEST 0
./adaptiveDTW ./Gun_Point/Gun_Point_TRAIN ./Gun_Point/Gun_Point_TEST 0
./adaptiveDTW ./HandOutlines/HandOutlines_TRAIN ./HandOutlines/HandOutlines_TEST 0
./adaptiveDTW ./Haptics/Haptics_TRAIN ./Haptics/Haptics_TEST 0
./adaptiveDTW ./InlineSkate/InlineSkate_TRAIN ./InlineSkate/InlineSkate_TEST 0
./adaptiveDTW ./ItalyPowerDemand/ItalyPowerDemand_TRAIN ./ItalyPowerDemand/ItalyPowerDemand_TEST 0
./adaptiveDTW ./Lighting2/Lighting2_TRAIN ./Lighting2/Lighting2_TEST 0
./adaptiveDTW ./Lighting7/Lighting7_TRAIN ./Lighting7/Lighting7_TEST 0
./adaptiveDTW ./MALLAT/MALLAT_TRAIN ./MALLAT/MALLAT_TEST 0
./adaptiveDTW ./mallet/MALLET_TRAIN ./mallet/MALLET_TEST 0
./adaptiveDTW ./MedicalImages/MedicalImages_TRAIN ./MedicalImages/MedicalImages_TEST 0
./adaptiveDTW ./MoteStrain/MoteStrain_TRAIN ./MoteStrain/MoteStrain_TEST 0
./adaptiveDTW ./NonInvasiveFatalECG/NonInvasiveFatalECG_Thorax1_TRAIN ./NonInvasiveFatalECG/NonInvasiveFatalECG_Thorax1_TEST 0
./adaptiveDTW ./NonInvasiveFatalECG/NonInvasiveFatalECG_Thorax2_TRAIN ./NonInvasiveFatalECG/NonInvasiveFatalECG_Thorax2_TEST 0
./adaptiveDTW ./OliveOil/OliveOil_TRAIN ./OliveOil/OliveOil_TEST 0
./adaptiveDTW ./OSULeaf/OSULeaf_TRAIN ./OSULeaf/OSULeaf_TEST 0
./adaptiveDTW ./Passgraph/Passgraph_TRAIN ./Passgraph/Passgraph_TEST 0
./adaptiveDTW ./shield/shield_TRAIN ./shield/shield_TEST 0
./adaptiveDTW ./SonyAIBORobotSurface/SonyAIBORobotSurface_TRAIN ./SonyAIBORobotSurface/SonyAIBORobotSurface_TEST 0
./adaptiveDTW ./SonyAIBORobotSurfaceII/SonyAIBORobotSurfaceII_TRAIN ./SonyAIBORobotSurfaceII/SonyAIBORobotSurfaceII_TEST 0
./adaptiveDTW ./StarLightCurves/StarLightCurves_TRAIN ./StarLightCurves/StarLightCurves_TEST 0
./adaptiveDTW ./SwedishLeaf/SwedishLeaf_TRAIN ./SwedishLeaf/SwedishLeaf_TEST 0
./adaptiveDTW ./Symbols/Symbols_TRAIN ./Symbols/Symbols_TEST 0
./adaptiveDTW ./synthetic_control/synthetic_control_TRAIN ./synthetic_control/synthetic_control_TEST 0
./adaptiveDTW ./Trace/Trace_TRAIN ./Trace/Trace_TEST 0
./adaptiveDTW ./Two_Patterns/Two_Patterns_TRAIN ./Two_Patterns/Two_Patterns_TEST 0
./adaptiveDTW ./TwoLeadECG/TwoLeadECG_TRAIN ./TwoLeadECG/TwoLeadECG_TEST 0
./adaptiveDTW ./uWaveGestureLibrary_X/uWaveGestureLibrary_X_TRAIN ./uWaveGestureLibrary_X/uWaveGestureLibrary_X_TEST 0
./adaptiveDTW ./uWaveGestureLibrary_Y/uWaveGestureLibrary_Y_TRAIN ./uWaveGestureLibrary_Y/uWaveGestureLibrary_Y_TEST 0
./adaptiveDTW ./uWaveGestureLibrary_Z/uWaveGestureLibrary_Z_TRAIN ./uWaveGestureLibrary_Z/uWaveGestureLibrary_Z_TEST 0
./adaptiveDTW ./wafer/wafer_TRAIN ./wafer/wafer_TEST 0
./adaptiveDTW ./WordsSynonyms/WordsSynonyms_TRAIN ./WordsSynonyms/WordsSynonyms_TEST 0
./adaptiveDTW ./yoga/yoga_TRAIN ./yoga/yoga_TEST 0
